language: node_js

node_js:
  - 0.10

# Travis supports running a real browser (Firefox) with a virtual screen. Just update your .travis.yml to set up the virtual screen like this:
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

# whitelist
# branches:
#  only:
#    - master
bundler_args: --retry 3

notifications:
  email:
    recipients:
      - lingsync-support@googlegroups.com
    on_success: change
    on_failure: always

# env:
#   matrix:
    # see set_up_new_machine.sh

before_install:
  # Download and configure deps
  - export TZ=Canada/Eastern # http://stackoverflow.com/questions/23371542/how-do-i-configure-travis-ci-to-use-the-correct-time-zone-for-a-rails-app
  - echo n | bash scripts/set_fielddb_version.sh
  - sudo apt-get install ncftp
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g jasmine-node
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install d3
  - npm install node-jsdom
  - npm install memory

before_script:
  # Make sure the emulator has started before running tests

script: grunt travis

env:
  global:
    - secure: sx0nyAy4yp4SACA05Q69CoUeeRuEu08rUqB448Ap1MVJgA5UAYlSht1g9nJdvCqBg8V3YEdIcGdov8vUmzwwU+mbdf7ssmrc9ecmq2j/iym6DCgrV5fJgRH4Fti0RGs9QcqgvpXejKWeHz/JIxlLqvcAKgZMcImMvF2gUfi6neQ=
    - secure: RiN997luw/gns/SKnHXeJQlFv6RQoVqpwIGslImO9Eam3NmNjL6OvDMFkKsxIFvtnOwH8+sixcd854IvcvxH0nONDT+aGm3PEIN0hI6O+7jya8XHWfTMaHrLX3D+iPsyq69QBN43hnyoT6e3WUxokJVq1LZeU2Rdi6rw04uuV/0=
    - secure: R7DYAAHx52YfRc2vJquODs/02U+D+TqcU9yYG67nvVzk5udWCjOdMFct8t3+1hFig+ITEy05cNr01r8rMnQmHbqILenmQgv9poiOncM8W4eeWi0x13exJT7BAJ8SCMyi4vWy+3qE0T1IPyI2XDdzLWBU8eocWRe9TtO0d/yseKw=
    - TIMEOUT=1000
after_success:
  # on:
  #   branch: master
  #   condition: $TRAVIS_REPO_SLUG = "FieldDB/FieldDB"
  - echo branch $TRAVIS_BRANCH
  - echo repo $TRAVIS_REPO_SLUG
  - touch "angular_client/modules/spreadsheet/dist/deployed at `date`"
  # - NOW=`date` && sed "s/\(appVersion = \"[^,]*ss\)\"/\1 $NOW\"/" angular_client/modules/spreadsheet/dist/scripts/scripts.js  > output && echo $NOW
  # - mv output angular_client/modules/spreadsheet/dist/scripts/scripts.js
  # - '[ "${TRAVIS_PULL_REQUEST}" = "false" ]  && [ "${TRAVIS_REPO_SLUG}" = "FieldDB/FieldDB" ]  && ncftpput -R -v -u $USERNAME -p $PASSWORD $SERVER / angular_client/modules/spreadsheet/dist/*'
