#!/bin/bash
./node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
httpredirectapp.js

./node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
app.js
