#!/bin/bash

#sudo service couchdb start
#sudo service mongod start
./node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
httpredirectapp.js

./node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
app.js
