exports.runTests = function(basePath) {
  if (!basePath) {
    basePath = "./";
  }
  console.log("dirname", __dirname);
  require(basePath + "Collection-spec");
  require(basePath + "FieldDBObject-spec");
  require(basePath + "FieldDB-spec");
  require(basePath + "activity/Activity-spec");
  require(basePath + "app/App-spec");
  require(basePath + "audioVideo/AudioVideoRecorder-spec");
  require(basePath + "audioVideo/AudioVideos-spec");
  require(basePath + "audioVideo/AudioWebService-spec");
  require(basePath + "authentication/Authentication-spec");
  require(basePath + "comment/Comment-spec");
  require(basePath + "confidentiality_encryption/Confidential-spec");
  require(basePath + "corpus/CorpusMask-spec");
  require(basePath + "corpus/Corpus-spec");
  require(basePath + "corpus/CorpusWebService-spec");
  require(basePath + "corpus/Database-spec");
  require(basePath + "data_list/DataList-spec");
  require(basePath + "datum/DatumFields-spec");
  require(basePath + "datum/DatumMenu-spec");
  require(basePath + "datum/DatumMenuView-spec");
  require(basePath + "datum/DatumStatus-spec");
  require(basePath + "datum/DatumTag-spec");
  require(basePath + "datum/Datum-spec");
  require(basePath + "datum/Session-spec");
  require(basePath + "export/Export-spec");
  require(basePath + "glosser/Glosser-spec");
  require(basePath + "hotkey/HotKey-spec");
  require(basePath + "image/Images-spec");
  require(basePath + "import/Import-spec");
  require(basePath + "insert_unicode/InsertUnicode-spec");
  require(basePath + "locales/Contextualizer-spec");
  require(basePath + "permission/Permission-spec");
  require(basePath + "search/Search-spec");
  require(basePath + "user/Bot-spec");
  require(basePath + "user/Consultant-spec");
  require(basePath + "user/Team-spec");
  require(basePath + "user/UserGeneric-spec");
  require(basePath + "user/UserPreference-spec");
};
