require([ "backbone", "crypto",
		"confidentiality_encryption/Confidential" ], 
		function(Backbone, CryptoJS, Confidential) {

	describe("Test Confidentiality Module", function() {
		it("should encrypt and decrypt strings ", function() {
			var message = "this is a sample confidential translation";
			var confidential = new Confidential();
			expect(confidential.decrypt(confidential.encrypt(message)) == message).toBeTruthy();
		});
		it("should let the app set the top secret encryption key", function() {
			var message = "this is a sample confidential translation";
			var confidential = new Confidential();
			confidential.set("secretkey", "thisisnormallyatopsecretautogeneratedkey");
			expect(confidential.decrypt(confidential.encrypt(message)) == message).toBeTruthy();
		});
		it("should let the app send in the top secret encryption key", function() {
			var confidential = new Confidential({secretkey: "thisisnormallyatopsecretautogeneratedkey"});
			expect(confidential.get("secretkey") == "thisisnormallyatopsecretautogeneratedkey").toBeTruthy();
		});
	});
});
