var Confidential = Confidential || require("../../api/confidentiality_encryption/Confidential");

xdescribe("Confidential: as a language consultant I want to be able to give data and have my data remain confidential", function() {
  it("should encrypt and decrypt strings ", function() {
    var message = "this is a sample confidential translation";
    var confidential = new Confidential();
    confidential.initialize({
      "filledWithDefaults": true
    });
    confidential.decryptedMode = true;
    expect(confidential.decrypt(confidential.encrypt(message)).indexOf(message) == 0).toBeTruthy();
  });
  it("should let the app set the top secret encryption key", function() {
    var message = "this is a sample confidential translation";
    var confidential = new Confidential();
    confidential.decryptedMode = true;

    confidential.set("secretkey", "thisisnormallyatopsecretautogeneratedkey");
    expect(confidential.decrypt(confidential.encrypt(message)).indexOf(message) == 0).toBeTruthy();
  });
  it("should let the app send in the top secret encryption key", function() {
    var confidential = new Confidential({
      secretkey: "thisisnormallyatopsecretautogeneratedkey"
    });
    confidential.decryptedMode = true;
    expect(confidential.get("secretkey") == "thisisnormallyatopsecretautogeneratedkey").toBeTruthy();
  });
});
